spring:
  application:
    name: spring-gemini-ai

  ai:
    model:
      chat: google-genai
    google:
      genai:
        api-key: AIzaSyDBRqWgWKyYmhYZl5kFfTWm81t3Pu28Or4
        chat:
          options:
            model: gemini-2.0-flash
            temperature: 0.7

server:
  port: 8081